[package]
name = "vfb-macros"
version = "0.1.5"
edition = "2021"
license = "GPL-3.0-or-later OR LGPL-3.0-or-later"
authors = ["Jens Kutilek <webmail@kutilek.de>"]
repository = "https://github.com/jenskutilek/vfbLib-rust"
description = "Procedural macros for VFB format handling"

[lib]
proc-macro = true

[dependencies]
error-stack = "0.8.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full"] }
