[package]
name = "vfb-macros"
version = "0.1.6"
edition = "2021"
description = "Procedural macros for VFB format handling"
repository = "https://github.com/jenskutilek/vfbLib-rust"
license = "GPL-3.0-or-later OR LGPL-3.0-or-later"

[lib]
proc-macro = true

[dependencies]
error-stack = "0.8.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full"] }
